def createVersion() {
    Date d = new Date()
    TimeZone tz = TimeZone.getTimeZone('Asia/Shanghai')
    return d.format('yyyyMMddHHmm', tz)
}

pipeline {
    agent any

    environment {
        TAG = createVersion()
        REPO_URL = "xxxxxx"
        REPO_NAME = "xxxxxx"
        APP = "${rootArtifactId}"
    }

    stages {
        stage('mvn package') {
            steps {
                sh '''mvn -B -DskipTests clean package'''
            }
        }

        stage('docker build') {
            steps {
                sh '''docker build -t ${REPO_URL}/${REPO_NAME}/${APP}:${TAG} .
                      docker push ${REPO_URL}/${REPO_NAME}/${APP}:${TAG}'''
                echo "${env.REPO_URL}/${env.REPO_NAME}/${env.APP}:${env.TAG}"
            }
        }
    }
}